buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
    }
}


plugins {
    id 'com.android.library'
    id 'maven-publish'
}


repositories {
    mavenLocal()
    google()
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

android {
    compileSdkVersion 34

    defaultConfig {
        minSdkVersion 23
        versionCode 1
        versionName '0.7.3'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation "com.github.tternes:jni-utils-rs:14244d5"
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                groupId = "com.github.tternes"
                from components.release
            }
        }
    }
}
