buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
    }
}


plugins {
    id 'com.android.library'
}


repositories {
    mavenLocal()
    google()
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

android {
    compileSdkVersion 34

    defaultConfig {
        minSdkVersion 23
        versionCode 1
        versionName '0.7.3'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation "com.github.tternes:jni-utils-rs:14244d5"
}
